services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - /home/anto/Workspace/Container/FlightServices/flightservices/flightservices/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  flightservice:
    image: antoconn/flightservices-flightservice:latest
    depends_on:
      - mysql
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reservation
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - /home/anto/Workspace/Container/FlightServices/flightservices/flightservices/logs:/app/logs   # ‚Üê mount logs folder to host

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.19.2
    depends_on:
      - elasticsearch
    volumes:
      - /home/anto/Workspace/Container/FlightServices/flightservices/flightservices/logs:/usr/share/logstash/pipeline/logs
      - /home/anto/Workspace/Container/FlightServices/flightservices/flightservices/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.19.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

volumes:
  mysql_data:
  es_data:
